resolver: nightly-2024-05-10

packages:
- '.'
- extract-hackage-info

extra-deps:
- ghc-lib-parser-9.10.1.20240511
- Cabal-syntax-3.12.0.0
- choice-0.2.4.1

nix:
  packages:
    - haskellPackages.happy
