resolver: nightly-2025-01-15

packages:
- '.'
- extract-hackage-info

extra-deps:
- ghc-lib-parser-9.12.1.20250105
- Cabal-syntax-3.14.1.0
- path-0.9.6
- path-io-1.8.2

allow-newer: true
allow-newer-deps: [path]

flags:
  path:
    os-string: true

nix:
  packages:
    - haskellPackages.happy
