resolver: lts-19.20

packages:
- '.'
- extract-hackage-info

extra-deps:
- Cabal-syntax-3.8.1.0
- ghc-lib-parser-9.4.1.20220807
- text-2.0.1
- parsec-3.1.16.1
- hashable-1.4.2.0
- data-array-byte-0.1.0.1

nix:
  packages:
    - haskellPackages.happy
