steps:
  - label: Build and test with GHC 8.8.4
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc884
    timeout: 100
  - label: Build and test with GHC 8.10.5
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc8105
    timeout: 100
  - label: Build and test with GHC 9.0.1
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc901
    timeout: 100
  - wait
  - label: Check formatting
    command: |
      ./format.sh
      git diff --exit-code --color=always
