steps:
  - label: Build and test with GHC 8.10.7
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc8107
    timeout: 100
  - label: Build and test with GHC 9.0.1
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc901
    timeout: 100
  - label: Build and test with GHC 9.2.1
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc921
    timeout: 100
  - wait
  - label: Check formatting
    command: |
      ./format.sh
      git diff --exit-code --color=always
  - wait
  - label: Build and deploy Ormolu Live
    command: |
      if [[ $BUILDKITE_BRANCH == "master" ]]; then
        ormolu-live/deploy.sh
      else
        nix-build -A ormoluLive.ormoluLive --arg ormoluLiveLink false -j 1
      fi
    timeout: 100
