steps:
  - label: Build and test with GHC 9.0.2
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc902
    timeout: 100
  - label: Build and test with GHC 9.2.4
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc924
    timeout: 100
  - wait
  - label: Check formatting
    command: |
      ./format.sh
      git diff --exit-code --color=always
  - wait
  - label: Build and deploy Ormolu Live
    command: |
      if [[ $BUILDKITE_BRANCH == "master" ]]; then
        ormolu-live/deploy.sh
      else
        nix-build -A ormoluLive.ormoluLive -j 1 \
          --arg ormoluLiveLink false --argstr ormoluCompiler ghc8107
      fi
    timeout: 100
