steps:
  - label: Build and test with GHC 8.6.5
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc865
    timeout: 100
  - label: Build and test with GHC 8.8.4
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc884
    timeout: 100
  - label: Build and test with GHC 8.10.2
    command: |
      nix-build --keep-going --no-out-link --argstr ormoluCompiler ghc8102
    timeout: 100
  - wait
  - label: Check formatting
    command: |
      ./format.sh
      git diff --exit-code --color=always
